#!/usr/bin/env node
/**
 * setup.mjs
 * ──────────
 * Interactive setup: discovers environment, shows summary, saves config.
 *
 * Usage:
 *   node scripts/setup.mjs
 *   node scripts/setup.mjs --yes   (non-interactive, accept defaults)
 */

import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { homedir } from 'node:os'
import { createInterface } from 'node:readline'

const CONFIG_DIR  = join(homedir(), '.adaptive-director')
const CONFIG_PATH = join(CONFIG_DIR, 'config.yaml')

// ─── Helpers ──────────────────────────────────────────────────────────────────

function run(script, args = []) {
  try {
    const out = execFileSync(process.execPath, [script, ...args], {
      encoding: 'utf8', timeout: 15000,
      cwd: process.cwd(),
    })
    return JSON.parse(out.trim())
  } catch (e) {
    return null
  }
}

function ask(rl, question) {
  return new Promise(resolve => rl.question(question, resolve))
}

function icon(ok) { return ok ? '✓' : '✗' }

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const nonInteractive = process.argv.includes('--yes')
  const scriptDir = new URL('.', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')
  const discoverScript = join(scriptDir, 'discover.mjs')

  console.log('\n  Adaptive Director — Setup\n')
  console.log('  Discovering environment...\n')

  // ── 1. Run discovery ──────────────────────────────────────────────────────
  const discovery = run(discoverScript)

  if (!discovery) {
    console.error('  Error: discovery failed. Make sure Node.js 18+ is available.')
    process.exit(1)
  }

  // ── 2. Print agents ───────────────────────────────────────────────────────
  console.log('  Agents:')
  for (const [id, info] of Object.entries(discovery.agents ?? {})) {
    const mark = info.available ? '✓' : info.installed ? '~' : '✗'
    const note = info.available ? (info.version ?? 'available')
               : info.installed ? 'installed (auth unknown)'
               : 'not installed'
    console.log(`    ${mark} ${id.padEnd(14)} ${note}`)
  }

  // ── 3. Delegate fleet ────────────────────────────────────────────────────
  console.log('')
  const ds = discovery.delegateSkills ?? { installed: false, lanes: {} }
  if (ds.installed) {
    const laneNames = Object.keys(ds.lanes ?? {})
    console.log(`  ✓ delegate-skills fleet detected (${laneNames.length} lane(s))`)
    for (const [name, lane] of Object.entries(ds.lanes ?? {})) {
      console.log(`    ${name} → ${lane.implementer ?? lane.agent ?? '?'}${lane.model ? ' / ' + lane.model : ''}`)
    }
  } else {
    console.log('  ✗ delegate-skills fleet not detected')
    if (!nonInteractive) {
      const rl = createInterface({ input: process.stdin, output: process.stdout })
      const ans = await ask(rl, '\n  Install delegate-skills now? [y/N] ')
      rl.close()
      if (ans.trim().toLowerCase() === 'y') {
        console.log('\n  Run:  npx skills add amElnagdy/delegate-skills')
        console.log('  Then: node scripts/setup.mjs\n')
        process.exit(0)
      }
    }
  }

  // ── 4. Write config ───────────────────────────────────────────────────────
  mkdirSync(CONFIG_DIR, { recursive: true })

  const config = [
    '# Adaptive Orchestrator config',
    '# Generated by setup.mjs',
    '',
    'defaultBudget: balanced',
    '',
    '# Agent overrides (uncomment and edit to override routing):',
    '# agentOverrides.plan: claude',
    '# agentOverrides.implement: codex',
    '# agentOverrides.review: claude',
    '# agentOverrides.verify: claude',
    '',
  ].join('\n')

  writeFileSync(CONFIG_PATH, config, 'utf8')

  console.log('\n  Default policies:')
  console.log('    Budget:    balanced')
  console.log('    Delegate:  disabled (use --delegate at runtime)')
  console.log('    Max:       disabled (use --allow-max at runtime)')
  console.log('')
  console.log(`  Setup complete. Config: ${CONFIG_PATH}`)
  console.log('')
}

main().catch(err => {
  console.error('Setup error:', err.message)
  process.exit(1)
})
